<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="project" nsURI="acs_project_mission" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="Coordinates">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Area">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="radius" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="center" eType="#//Coordinates"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Obstacle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="area" eType="#//Area" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Robot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="#//Coordinates"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intProperties" upperBound="-1"
        eType="#//IntProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stringProperties" upperBound="-1"
        eType="#//StringProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doubleProperties" upperBound="-1"
        eType="#//DoubleProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensors" upperBound="-1"
        eType="#//Sensor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="batteries" upperBound="-1"
        eType="#//Battery" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="motionSources" upperBound="-1"
        eType="#//MotionSource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Server">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intProperties" upperBound="-1"
        eType="#//IntProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stringProperties" upperBound="-1"
        eType="#//StringProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doubleProperties" upperBound="-1"
        eType="#//DoubleProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SensorType">
    <eLiterals name="GPS_POSITION" value="1"/>
    <eLiterals name="DEPTH" value="2"/>
    <eLiterals name="TEMPERATURE" value="3"/>
    <eLiterals name="PRESSURE" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="energyPerSample" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="samplesPerSecond" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SensorType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MotionSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="energyPerDistanceUnit"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Battery">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalEnergy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="goal_ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//Robot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//Server"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="header" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" upperBound="-1" eType="#//MessageData"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GoalMembers">
    <eStructuralFeatures xsi:type="ecore:EReference" name="goalMembers" upperBound="-1"
        eType="#//Robot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GoalDependencies">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//Goal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GoalArea">
    <eStructuralFeatures xsi:type="ecore:EReference" name="goalArea" eType="#//Area"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Patrol">
    <eStructuralFeatures xsi:type="ecore:EReference" name="area" eType="#//Area" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Visit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinates" eType="#//Coordinates"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Track">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trajectory" upperBound="-1"
        eType="#//Coordinates" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stay">
    <eStructuralFeatures xsi:type="ecore:EReference" name="area" eType="#//Area" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AvoidCollision">
    <eStructuralFeatures xsi:type="ecore:EReference" name="robots" upperBound="-1"
        eType="#//Robot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="obstacles" upperBound="-1"
        eType="#//Obstacle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FixedDistanceBetweenRobots">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fixedDistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StayWithinMissionArea"/>
  <eClassifiers xsi:type="ecore:EClass" name="GatherSamples">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetSampleNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" eType="#//Sensor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SufficientEnergy"/>
  <eClassifiers xsi:type="ecore:EClass" name="GoalTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patrol" eType="#//Patrol"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="visit" eType="#//Visit"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="track" eType="#//Track"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stay" eType="#//Stay" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="avoidCollision" eType="#//AvoidCollision"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fixedDistanceBetweenRobots"
        eType="#//FixedDistanceBetweenRobots" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gatherSamples" eType="#//GatherSamples"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sufficientEnergy" eType="#//SufficientEnergy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stayWithinMissionArea"
        eType="#//StayWithinMissionArea" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" eType="#//GoalMembers"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependentGoals" eType="#//GoalDependencies"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="area" eType="#//GoalArea"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" eType="#//GoalTask"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1"
        eType="#//Message" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mission">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="robots" upperBound="-1"
        eType="#//Robot" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="servers" upperBound="-1"
        eType="#//Server" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goals" upperBound="-1"
        eType="#//Goal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="obstacles" upperBound="-1"
        eType="#//Obstacle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="missionArea" eType="#//Area"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
