<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="project" nsURI="acs_project_setup" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="FaultSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faults" upperBound="-1"
        eType="ecore:EClass ../ecore/fault.ecore#//Fault" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Setup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mission" eType="ecore:EClass ../ecore/mission.ecore#//Mission"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" upperBound="-1"
        eType="#//FaultSpecification" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
